### ISSUE TITLE
Unable to point to git repo as drop-in bazel replacement for release

### ISSUE THREAD

**Issue by segiddins** [google/xctestrunner#19]
One of the things that makes contributing to this repo difficult (as @keith alluded to in https://github.com/bazelbuild/rules_apple/issues/495#issuecomment-529756077) is that the xctestrunner git repo can't be used as a drop-in replacement for the released archive when using bazel.

The release archive has its test runner executable available as `@xctestrunner//file:file`, which does not exist in this repo at all.

I tried to work around this by adding

```startlark
patch_cmds = ["""
        mkdir file
        echo 'alias(name = "file", actual = "//xctestrunner:ios_test_runner.par", visibility = ["//visibility:public"])' > file/BUILD.bazel
        """]
```

to my `WORKSPACE`'s `git_repository` for `xctestrunner`, but then I get Python errors:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "../xctestrunner/xctestrunner/ios_test_runner.par/__main__.py", line 33, in <module>
ModuleNotFoundError: No module named 'xctestrunner.shared'
```

Ideally, we'd be able to point our `@xctestrunner` to the git repo when necessary, but currently I don't see how that's possible

**Comment by segiddins** [comment]
I think https://github.com/bazelbuild/bazel/issues/7067 might be the blocker here -- I think the `par`/`py_binary` produced by `xctestrunner:ios_test_runner.par` differs when built as the root?/non-external repository, vs as an external repository
